config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#introductiepagina'

  get 'introductiepagina', to: 'static_pages#introductiepagina', as: :introductiepagina
  get 'verkoopverhalltje_maar_dan_uitgebreider', to: 'static_pages#verkoopverhalltje_maar_dan_uitgebreider', as: :verkoopverhalltje_maar_dan_uitgebreider
  get 'tarieven_voor_geld', to: 'static_pages#tarieven_voor_geld', as: :tarieven_voor_geld
  get 'betalen_met_spullen', to: 'static_pages#betalen_met_spullen', as: :betalen_met_spullen
  get 'werkwijze', to: 'static_pages#werkwijze', as: :werkwijze
  get 'about', to: 'static_pages#about', as: :about

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def introductiepagina
  end 

  def verkoopverhalltje_maar_dan_uitgebreider
  end

  def tarieven_voor_geld
  end

  def betalen_met_spullen
  end

  def werkwijze
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
      <!--%= link_to image_tag('gypper_logo.png', id: "logo"), root_path, class: 'navbar-brand', id: "home" %-->
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Introductiepagina", root_path  %></li>
        <li><%= link_to "Verkoopverhalltje, maar dan uitgebreider", verkoopverhalltje_maar_dan_uitgebreider_path  %></li>
        <li><%= link_to "Tarieven voor geld", tarieven_voor_geld_path  %></li>
        <li><%= link_to "Betalen met spullen", betalen_met_spullen_path  %></li>
        <li><%= link_to "Werkwijze", werkwijze_path  %></li>
        <li><%= link_to "About", about_path  %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? "Gypper | #{yield(:title)}" : "Gypper" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Gypper" %>">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'layouts/navigation' %>
  </header>
  <main role="main">
    <%= yield %>
  </main>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide :title, "About"  %>

app/views/static_pages/betalen_met_spullen.html.erb
<% provide :title, "Betalen met spullen"  %>
<div class="container mar-t-3-pc">
  <div class="row">
    <div class="col-md-4">
      <%= t("text.betalen_met_spullen.page_header")  %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= t("text.betalen_met_spullen.possibly_accepted_shit.header")  %>
      <ul>
        <li><%= t("text.betalen_met_spullen.possibly_accepted_shit.furniture") %></li>
        <li><%= t("text.betalen_met_spullen.possibly_accepted_shit.watches") %></li>
        <li><%= t("text.betalen_met_spullen.possibly_accepted_shit.phones") %></li>        
        <li><%= t("text.betalen_met_spullen.possibly_accepted_shit.toys") %></li>        
        <li><%= t("text.betalen_met_spullen.possibly_accepted_shit.comics") %></li>        
        <li><%= t("text.betalen_met_spullen.possibly_accepted_shit.tools") %></li>               
        <li><%= t("text.betalen_met_spullen.possibly_accepted_shit.liquor") %></li>        
        <li><%= t("text.betalen_met_spullen.possibly_accepted_shit.wii_games") %></li>        
        <li><%= t("text.betalen_met_spullen.possibly_accepted_shit.linens") %></li>        
        <li><%= t("text.betalen_met_spullen.possibly_accepted_shit.pallets") %></li>        
        <li><%= t("text.betalen_met_spullen.possibly_accepted_shit.any_ideas") %></li>                
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= t("text.betalen_met_spullen.possibly_accepted_sevices.header")  %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= t("text.betalen_met_spullen.possibly_accepted_sevices.shit_i_dont_like")  %>
      <ul>
        <li><%= t("text.betalen_met_spullen.possibly_accepted_sevices.taxes")%></li>
      </ul>
    </div>
  </div>

</div>

app/views/static_pages/home.html.erb
<% provide :title, "Home"  %>
<h1>Home</h1>
<p>You better get your head and your ass wired together, or I will take a giant shit on you.</p>

app/views/static_pages/introductiepagina.html.erb
<% provide :title, "Introductiepagina"  %>
<div class="container-fluid mar-t-8-pc">
  <div class="row">
    <div class="col-md-4 col-md-offset-2">
      <h1><b>SHITCORRECTIE</b></h1>    
      <p>
        Correctie van allerlei tekstuele shit en meer.<br>
        Fxxxing cheap ass fou<s>d</s>t-removal uit je te<s>x</s>kst! <br>
        (maar altijd binnen vier dagen en wel gewoon goed, weet je) <br>       
        Betalen met geld, of met spullen of wederdiensten.        
      </p>    
    </div>
  </div>
</div

app/views/static_pages/tarieven_voor_geld.html.erb
<% provide :title, "Tarieven voor geld"  %>
<div class="container mar-t-3-pc">
    <div class="row">
        <div class="col-md-4">
          <h4><%= t("text.tarieven_voor_betalen_met_geld.obvious_errors.header") %></h4>
        </div>
        <div class="col-md-4">
          <h4><%= t("text.tarieven_voor_betalen_met_geld.must_haves.header") %></h4>
        </div>
        <div class="col-md-4">
          <h4><%= t("text.tarieven_voor_betalen_met_geld.would_haves.header")  %></h4>
       </div>
   </div>
   <div class="row">
       <div class="col-md-4">
          <%= t("text.tarieven_voor_betalen_met_geld.obvious_errors.costs")  %>
       </div>
       <div class="col-md-4">
          <%= t("text.tarieven_voor_betalen_met_geld.must_haves.costs")  %>
       </div>
       <div class="col-md-4">
          <%= t("text.tarieven_voor_betalen_met_geld.would_haves.costs")  %>
       </div>
   </div>    
   <div class="row">
       <div class="col-md-4">
          <%= t("text.tarieven_voor_betalen_met_geld.obvious_errors.specs")  %>
       </div>
       <div class="col-md-4">
          <%= t("text.tarieven_voor_betalen_met_geld.must_haves.specs")  %>
       </div>
       <div class="col-md-4">
          <%= t("text.tarieven_voor_betalen_met_geld.would_haves.specs")  %>
       </div>
   </div>        
   <div class="row">
      <div class="col-md-4">
          <ul>
              <li><%= t("text.tarieven_voor_betalen_met_geld.obvious_errors.example1")  %></li>
              <li><%= t("text.tarieven_voor_betalen_met_geld.obvious_errors.example2")  %></li>
              <li><%= t("text.tarieven_voor_betalen_met_geld.obvious_errors.example3")  %></li>
              <li><%= t("text.tarieven_voor_betalen_met_geld.obvious_errors.example4")  %></li>
              <li><%= t("text.tarieven_voor_betalen_met_geld.obvious_errors.example5")  %></li>
              <li><%= t("text.tarieven_voor_betalen_met_geld.obvious_errors.example6")  %></li>
              <li><%= t("text.tarieven_voor_betalen_met_geld.obvious_errors.example7")  %></li>
          </ul>

      </div>
      <div class="col-md-4">
          <ul>
              <li><%= t("text.tarieven_voor_betalen_met_geld.must_haves.example1")  %></li>
              <li><%= t("text.tarieven_voor_betalen_met_geld.must_haves.example2")  %></li>
              <li><%= t("text.tarieven_voor_betalen_met_geld.must_haves.example3")  %></li>
          </ul>
      </div>
      <div class="col-md-4">
          <ul>
              <li><%= t("text.tarieven_voor_betalen_met_geld.would_haves.example1")  %></li>
              <li><%= t("text.tarieven_voor_betalen_met_geld.would_haves.example2")  %></li>
              <li><%= t("text.tarieven_voor_betalen_met_geld.would_haves.example3")  %></li>
          </ul>
      </div>
   </div>
   <div class="row">
      <div class="col-md-12">
         <%= t("text.tarieven_voor_betalen_met_geld.extra_services")  %>
      </div>
      <div class="col-md-12">
         <%= t("text.tarieven_voor_betalen_met_geld.overnight_services")  %>
      </div> 
      <div class="col-md-12">
         <%= t("text.tarieven_voor_betalen_met_geld.percentage_50")  %>
      </div>    
   </div>
</div>

app/views/static_pages/verkoopverhalltje_maar_dan_uitgebreider.html.erb
<% provide :title, "Verkoopverhalltje, maar dan uitgebreider"  %>

<div class="container mar-t-3-pc">
   <div class="row">
       <div class="col-md-4">
          <h4><%= t("text.verkoopverhalltje_maar_dan_uitgebreider.error_removal.header") %></h4>
       </div>
       <div class="col-md-4">
           <h4><%= t("text.verkoopverhalltje_maar_dan_uitgebreider.cheap.header") %></h4>
       </div>
       <div class="col-md-4">
           <h4><%= t("text.verkoopverhalltje_maar_dan_uitgebreider.more.header") %></h4>
       </div>
   </div>
   <div class="row">
       <div class="col-md-4">
           <%= t("text.verkoopverhalltje_maar_dan_uitgebreider.error_removal.content") %>
       </div>
       <div class="col-md-4">
           <%= t("text.verkoopverhalltje_maar_dan_uitgebreider.cheap.content") %>
       </div>
       <div class="col-md-4">
           <%= t("text.verkoopverhalltje_maar_dan_uitgebreider.more.content") %>
       </div>
   </div>
</div>

app/views/static_pages/werkwijze.html.erb
<% provide :title, "Werkwijze"  %>
<div class="container mar-t-3-pc">
   <div class="row">
      <div class="col-md-6">
         <%= t("text.werkwijze.step1.title") %>
      </div>
      <div class="col-md-6">
         <%= t("text.werkwijze.step1.comment") %>
      </div>
   </div>
   <div class="row">
      <div class="col-md-6">
          <%= t("text.werkwijze.step2.comment") %>
      </div>
      <div class="col-md-6">
          <%= t("text.werkwijze.step2.title") %>
      </div>
   </div>   
   <div class="row">
      <div class="col-md-6">
          <%= t("text.werkwijze.step3.title") %>
      </div>
      <div class="col-md-6">
          <%= t("text.werkwijze.step3.comment") %>
      </div>
   </div> 
   <div class="row">
       <div class="col-md-6">
           <%= t("text.werkwijze.step4.comment") %>
       </div>
       <div class="col-md-6">
           <%= t("text.werkwijze.step4.title") %>
       </div>
   </div>  
   <div class="row">
       <div class="col-md-6">
          <%= t("text.werkwijze.step5.title") %>
       </div>
       <div class="col-md-6">
          <%= t("text.werkwijze.step5.comment") %>
       </div>
   </div>  
   <div class="row">
       <div class="col-md-6">
           <%= t("text.werkwijze.step6.comment") %>
       </div>
       <div class="col-md-6">
           <%= t("text.werkwijze.step6.title") %>
       </div>
   </div> 
   <div class="row">
       <div class="col-md-6">
          <%= t("text.werkwijze.step7.title") %>
      </div>
      <div class="col-md-6">
          <%= t("text.werkwijze.step7.comment") %>
      </div>
   </div>
   <div class="row">
      <div class="col-md-12">
          <%= t("text.werkwijze.pay_in_kind") %>
      </div>
   </div>  
</div>